# Generated by Django 5.2 on 2025-05-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2busers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('ar_SA', 'Arabic'), ('en_US', 'English')], default='ar_SA', max_length=20),
        ),
    ]
