# Generated by Django 5.2 on 2025-04-27 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '__first__'),
        ('product', '0012_producttranslation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('purchaseDate', models.DateTimeField()),
                ('status', models.CharField(choices=[('INT', 'Initial'), ('PND', 'Pending'), ('PRC', 'Processing'), ('DON', 'Done')], default='INT', max_length=3)),
                ('paymentMethod', models.CharField(choices=[('USD', 'United States Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('SAR', 'Saudi Arabian Riyal'), ('AED', 'United Arab Emirates Dirham'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar')], default='BLC', max_length=3)),
                ('purchaser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creationDate', models.DateTimeField()),
                ('currency', models.CharField(choices=[('USD', 'United States Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('SAR', 'Saudi Arabian Riyal'), ('AED', 'United Arab Emirates Dirham'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar')], default='SAR', max_length=3)),
                ('status', models.CharField(choices=[('INT', 'Initial'), ('PND', 'Pending'), ('PRC', 'Processing'), ('DON', 'Done')], default='INT', max_length=3)),
                ('quantity', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_items', to='company.branch')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='cart.cart')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='product.product')),
            ],
        ),
    ]
