# Generated by Django 5.2 on 2025-04-27 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_purchaser'),
        ('product', '0012_producttranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='product.product'),
        ),
    ]
