# Generated by Django 5.2 on 2025-04-27 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_productinstance_cart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='paymentMethod',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='purchaseDate',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.AlterField(
            model_name='cart',
            name='purchaser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='cart.cart'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseDate', models.DateTimeField(auto_now_add=True)),
                ('expirePaymentDate', models.DateTimeField()),
                ('status', models.CharField(choices=[('INT', 'Initial'), ('PND', 'Pending'), ('PRC', 'Processing'), ('DON', 'Done')], default='INT', max_length=3)),
                ('paymentMethod', models.CharField(choices=[('USD', 'United States Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('SAR', 'Saudi Arabian Riyal'), ('AED', 'United Arab Emirates Dirham'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar')], default='BLC', max_length=3)),
                ('purchaser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productinstance',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='cart.order'),
        ),
    ]
