# Generated by Django 5.2 on 2025-04-27 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_paymentmethod_remove_cart_purchasedate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='purchaser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activecart', to=settings.AUTH_USER_MODEL),
        ),
    ]
