# Generated by Django 5.2 on 2025-04-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymentMethod',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending'), ('ACC', 'Accepted'), ('RJC', 'Rejected')], default='PND', max_length=3),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending'), ('ACC', 'Accepted'), ('RJC', 'Rejected')], default='INT', max_length=3),
        ),
    ]
