# Generated by Django 5.2 on 2025-04-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_order_paymentmethod_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expirePaymentDate',
        ),
        migrations.AddField(
            model_name='invoice',
            name='expirePaymentDate',
            field=models.DateTimeField(default='2035-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.CharField(blank=True, null=True),
        ),
    ]
