# Generated by Django 5.2 on 2025-04-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_order_expirepaymentdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchaseDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
