# Generated by Django 5.2 on 2025-05-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_order_purchasedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
