# Generated by Django 5.2 on 2025-05-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_remove_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('UNP', 'Unpaid'), ('PRC', 'Processing'), ('UDL', 'To be delivered'), ('DLV', 'Delivered')], default='UNP', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='cart.order'),
        ),
    ]
