# Generated by Django 5.2 on 2025-06-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_order_delivered_datetime_order_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='rejection_reason',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending'), ('ACC', 'Accepted'), ('RJC', 'Rejected'), ('PRJ', 'Partial Rejected')], default='PND', max_length=3),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending'), ('ACC', 'Accepted'), ('RJC', 'Rejected'), ('PRJ', 'Partial Rejected')], default='INT', max_length=3),
        ),
    ]
