# Generated by Django 5.2 on 2025-04-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_attribut_product_attributs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='closest_category',
        ),
    ]
