# Generated by Django 5.2 on 2025-04-22 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_closest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='closest_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_products', to='product.category'),
        ),
    ]
