# Generated by Django 5.2 on 2025-04-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_closest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='groups',
            field=models.ManyToManyField(related_name='categories_groups', to='product.productgroup'),
        ),
    ]
