# Generated by Django 5.2 on 2025-04-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_categorytranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='custom_price',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter discount as a percentage (e.g., 10.00 for 10%).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='flat_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter flat discount amount (e.g., 50.00).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='percentage_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter percentage discount (e.g., 10.00 for 10%).', max_digits=5, null=True),
        ),
    ]
