# Generated by Django 5.2 on 2025-04-26 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_productprice_custom_price_product_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroupTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('productgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.productgroup')),
            ],
            options={
                'unique_together': {('productgroup', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ProductSubgroupTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('productsubgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.productsubgroup')),
            ],
            options={
                'unique_together': {('productsubgroup', 'language')},
            },
        ),
    ]
