# Generated by Django 5.2 on 2025-05-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_producttranslation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Field',
        ),
    ]
