# Generated by Django 5.2 on 2025-06-22 07:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_delete_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availibility',
            field=models.CharField(choices=[('M', 'Market'), ('S', 'Stock')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
