# Generated by Django 5.2 on 2025-06-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_availibility_alter_category_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.URLField(),
        ),
    ]
