# Generated by Django 5.2 on 2025-05-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='register_number',
            field=models.CharField(default='en_SA', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
