# Generated by Django 5.2 on 2025-05-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_register_number'),
        ('product', '0013_delete_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='2025-05-27', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='company.branch')),
                ('items', models.ManyToManyField(blank=True, related_name='contracts', to='product.product')),
            ],
        ),
    ]
