# Generated by Django 5.2 on 2025-06-22 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_address_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='company.branch'),
        ),
    ]
